/** Declaration file generated by dts-gen */

export = gosugamers_api;

declare function gosugamers_api(): void;

interface Match {
    url: string;
    home: {
        name: string;
        url: string;
        country: string;
        rank: number;
        score: number;
    },
    away: {
        name: string;
        url: string;
        country: string;
        rank: number;
        score: number;
    },
    vods: string[];
    status: string;
    type: string;
    rounds: string;
    valueBet: boolean;
    livestream: string;
    datetime: number;
}

interface fetchMatchUrlsCallback {
    (error: string, URLs: string[]): any;
}


interface parseMatchCallback {
    (error: string, match: Match): any;
}

interface parseMatchesCallback {
    (error: string, match: Match[]): any;
}

declare namespace gosugamers_api {

    function fetchMatchUrls(game: string, page?: number, callback?: fetchMatchUrlsCallback): void;

    function parseMatch(url: string, callback: parseMatchCallback): void;

    function parseMatches(urls: string[], callback: parseMatchesCallback): void;

}

