export class GenericChallenges {
    public static challenges: string[] = [
        "SO ... COLORFUL - YOU MUST TAKE PRISMATIC SHARD IF IT APPEARS",
        "FOLLOW DEREK'S ADVICE - IF THERE IS A CHANCE OR OPPORTUNITY FOR A CURSE, YOU MUST TAKE IT.",
        "YOU ARE THE BOMB! - NOT REALLY, BUT IF YOU SEE THE BOMB YOU MUST TAKE IT. MAKE MR TORGUE PROUD!",
        "DRINK UP! - TAKE ALL POTION RELATED RELICS AND CARDS.",
        "HEALTHY BOI! - TAKE ALL CHANCES TO INCREASE YOUR MAX HP (AS LONG AS IT DOESN'T KILL YOU).",
        "YOU GOT SOME BLOAT THERE - YOU CAN'T SKIP CARDS AT THE ENDS OF FIGHTS ANYMORE.",
        "NO MORE TOKING - YOU CAN NO LONGER REMOVE CARDS (IF YOU HAVE A CHOICE IN THE MATTER).",
        "MR POPULAR - YOU CAN NO LONGER JUST LEAVE AN EVENT WITHOUT DOING SOMETHING.",
        "THE MOST RIGHT WAY - YOU CAN'T SCROLL UP ON THE MAP. PRAY FOR WING BOOTS.",
        "MAXIMUM GREED - ALL CARDS AND RELICS THAT INCREASE YOUR GOLD MUST BE TAKEN.",
        "EMBRACE THE INSANITY - YOU MUST TAKE ALL MADNESS CARDS.",
        "CONTROLLED CHAOS - YOU MUST PICK UP AT LEAST ONE MAYHEM CARD IF AVAILABLE.",
        "HEARTBREAK - YOU REALLY WANT TO FACE THE HEART. YOU MUST TAKE HEART KEYS WHEN PRESENTED AND FACE THE SHINY IN ACT I."
    ];
    public static uniqueChallenges: SpireUniqueChallenge[] = [
        {
            challengeName: "SNECKO",
            challenges: [
                "PRAISE SNECKO - YOU MUST TAKE SNECKO EYE NO MATTER WHAT IF IT SHOWS.",
                "HERECY - YOU ARE FORBIDDEN FROM TAKING SNECKO EYE OR USING SNECKO OIL."
            ]
        },
        {
            challengeName: "BOSS_RELIC",
            challenges: [
                "DON'T CHOKE - IF THE CHOKER IS OFFERED, YOU MUST TAKE IT. (OVERWRITTEN BY \"PRAISE SNECKO\" OR CHARACTER SPECIFIC RULE)",
                "VOW OF POVERTY - IF ECTOPLASM IS OFFERED, YOU MUST TAKE IT. (OVERWRITTEN BY \"PRAISE SNECKO\" OR CHARACTER SPECIFIC RULE)",
                "NO SLEEP TIL ACT IV - IF COFFEE DRIPPER IS OFFERED, YOU MUST TAKE IT. (OVERWRITTEN BY \"PRAISE SNECKO\" OR CHARACTER SPECIFIC RULE)",
                "I WANT TO DIE TO BIRDS - IF PHILOSOPHER'S STONE IF OFFERED, YOU MUST TAKE IT. (OVERWRITTEN BY \"PRAISE SNECKO\" OR CHARACTER SPECIFIC RULE)",
                "PROHIBITION ERA RUN - IF SOZU IS OFFERED, YOU MUST TAKE IT. (OVERWRITTEN BY \"PRAISE SNECKO\" OR CHARACTER SPECIFIC RULE)",
                "DEREK SEES NO DOWNSIDE - IF CURSED KEY IS OFFERED, YOU MUST TAKE IT. (OVERWRITTEN BY \"PRAISE SNECKO\" OR CHARACTER SPECIFIC RULE)",
                "WILL WILL SMITH SMITH? NO - IF FUSION HAMMER IS OFFERED, YOU MUST TAKE IT. (OVERWRITTEN BY \"PRAISE SNECKO\" OR CHARACTER SPECIFIC RULE)",
                "SLAVES ARE SLAVES - IF SLAVER'S COLLAR IS OFFERED, YOU MUST TAKE IT. (OVERWRITTEN BY \"PRAISE SNECKO\" OR CHARACTER SPECIFIC RULE)"
            ]
        },
        {
            challengeName: "FIRE_RELICS",
            challenges: [
                "MASTER OF NONE - TAKE RELICS THAT GIVE YOU SOMETHING EXTRA TO DO AT FIRES WHENEVER POSSIBLE.",
                "DIG! - IF YOU SEE THE SHOVEL, YOU MUST TAKE IT. IF YOU HAVE THE SHOVEL, YOU MUST DIG.",
            ]
        }
    ];
}